name: weather_app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  connectivity_plus: ^2.2.1
  flutter_launcher_icons: "^0.9.0"
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-ExtraLight.ttf
          weight: 200
        - asset: fonts/Oswald-Light.ttf
          weight: 300
        - asset: fonts/Oswald-Regular.ttf
          weight: 400
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
