name: CI

on:
    push:
        tags: 
            -'*'
    # pull_request: 
    #     branches: 
    #         - master
    
jobs:
    flutter_test:
        name: Run flutter tests and analyze
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3      
            - uses: actions/setup-java@v3
              with: 
                distribution: 'oracle'
                java-version: '17.x'
            - uses: subosito/flutter-action@v2
            - run: flutter pub get
            - run: flutter analyze
            - run: flutter test

   
    build_android:
        name: Build Android
        needs: [flutter_test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3      
            - uses: actions/setup-java@v3
              with: 
                distribution: 'oracle'
                java-version: '17.x'
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.7.1'
            - run: flutter pub get
            - run: flutter test
            - run: flutter build apk
    release:
        name: Release   
        runs-on: ubuntu-latest
        # if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
            - uses: ncipollo/release-action@v1
              with:
                artifacts: 'build/app/outputs/flutter-apk/*.apk'
                token: ${{ secrets.TOKEN }} 


